# This program calculates the experiment-based differentially expressed proteins for each
# cell line at each drug-treated condition from the LFQ intensity results generated by
# MaxQuant.

# Load required library
library("utils")
library("stats")
library("matrixStats")
library("vsn")
library("limma")
library("metap")

# User home directory
home_dir <- Sys.getenv("HOME")
# The directory for input data files.
input_data_dir <- file.path(home_dir, "DToxS-DEP-Depot", "Input-Data")
# Set the directory for output table data files.
output_data_dir <- file.path(home_dir, "DToxS-DEP-Depot", "Output-Data")

# Name of control state.
state_name_ctrl <- "CTRL"
# The names of protein-ID and gene-name columns.
protein_ids_gene_names_col_names <- c("Protein.ID", "Majority.Protein.ID", "Gene.Name")
# The number of components contained in sample IDs.
n_sampple_id_compnts <- 7
# A total minimum number of 3 samples and at least 1 replicate from each group
# are required for DEP comparison.
n_total_compr_samples_min <- 3
# FDR threshold value.
fdr_thrsh <- 0.1
# Data table type.
data_table_type <- "tsv"
# Flag of verbose print.
verbose <- TRUE

# Calculate the group-wise accumulated sums.
cumsumGroups <- function(x)
{
    grp_sums <- rep(NA, times=length(x))
    val_freqs <- table(x)
    for (val in names(val_freqs))
    {
        val_flags <- x==val
        grp_sums[val_flags] <- 1:val_freqs[val]
    }
    return(grp_sums)
}

# Load experiment design table.
exprt_design_table_file_name <- paste("Experiment-Design-Table", data_table_type, sep=".")
exprt_design_table_file_path <- file.path(input_data_dir, exprt_design_table_file_name)
stopifnot(file.exists(exprt_design_table_file_path))
if(verbose) cat("Reading ", exprt_design_table_file_path, "...\n", sep="")
exprt_design_table <- read.delim(exprt_design_table_file_path, quote="", na.strings="", comment.char="#", check.names=FALSE, stringsAsFactors=FALSE)
if(verbose) cat("Finished reading ", exprt_design_table_file_path, "...\n", sep="")

# Load the LFQ intensity for sample treatments together with protein IDs and
# gene names.
protein_sample_lfq_file_name <- paste("Protein-Gene-Sample-LFQ-Intensity-Norm", data_table_type, sep=".")
protein_sample_lfq_file_path <- file.path(input_data_dir, protein_sample_lfq_file_name)
stopifnot(file.exists(protein_sample_lfq_file_path))
if(verbose) cat("Reading ", protein_sample_lfq_file_path, "...\n", sep="")
protein_sample_lfq <- read.delim(protein_sample_lfq_file_path, quote="", na.strings="", comment.char="#", check.names=FALSE, stringsAsFactors=FALSE)
if(verbose) cat("Finished reading ", protein_sample_lfq_file_path, "...\n", sep="")

# Pre-process LFQ intensity table.
protein_ids_gene_names <- protein_sample_lfq[,protein_ids_gene_names_col_names,drop=FALSE]
sample_lfq_intsty <- protein_sample_lfq[, !(colnames(protein_sample_lfq) %in% protein_ids_gene_names_col_names), drop=FALSE]
# Set all zero intensity values to NA.
sample_lfq_intsty[sample_lfq_intsty==0] <- NA

if(verbose) cat("\n", "Start calculating differentially expressed proteins from LFQ intensity data", "\n\n", sep="")

# Calculate the DEPs at each combination of cell line, drug treatment and experiment number.
cell_lines <- sort(unique(exprt_design_table$Cell))
drug_names <- sort(unique(exprt_design_table$State))
drug_names <- drug_names[!grepl(state_name_ctrl, drug_names)]
exprt_nums <- sort(unique(exprt_design_table$Experiment))
ctrl_flags <- exprt_design_table$State==state_name_ctrl

n_gross_compr_pairs <- 0
n_compr_pairs <- 0

# A list of DEP comparison statistics results.
dep_compr_stats_results_list <- list()
# A summary of combined DEP comparison statistics results.
dep_combn_compr_stats_sumry <- NULL
# A summary of DEP comparison statistics results.
dep_compr_stats_sumry <- NULL

compr_pair_idx_max <- 0
for (drug_name in drug_names)
{
    dep_compr_stats_results_list_drug <- list()
    drug_flags <- exprt_design_table$State==drug_name
    for (cell_line in cell_lines)
    {
        dep_compr_stats_results_list_drug_cell <- list()
        cell_flags <- exprt_design_table$Cell==cell_line
        for (exprt_num in exprt_nums)
        {
            exprt_flags <- exprt_design_table$Experiment==exprt_num
            drug_cell_exprt_flags <- drug_flags & cell_flags & exprt_flags
            ctrl_cell_exprt_flags <- ctrl_flags & cell_flags & exprt_flags

            # A total minimum number of 3 samples and at least 1 replicate from each group
            # are required for DEP comparison.
            if(!any(drug_cell_exprt_flags) || !any(ctrl_cell_exprt_flags) || sum(drug_cell_exprt_flags)+sum(ctrl_cell_exprt_flags)<n_total_compr_samples_min) next

            n_gross_compr_pairs <- n_gross_compr_pairs + 1
            if(verbose) cat("Gross comparison #", n_gross_compr_pairs, "\n", sep="")

            # Extract the LFQ intensity columns for current drug-treated samples and control samples.
            sample_lfq_intsty_drug_ctrl_cell_exprt <- cbind(sample_lfq_intsty[,drug_cell_exprt_flags,drop=FALSE], sample_lfq_intsty[,ctrl_cell_exprt_flags,drop=FALSE])
            exprt_design_table_drug_ctrl_cell_exprt <- rbind(exprt_design_table[drug_cell_exprt_flags,,drop=FALSE], exprt_design_table[ctrl_cell_exprt_flags,,drop=FALSE])
            exprt_design_drug_ctrl_cell_exprt <- data.frame(label=colnames(sample_lfq_intsty_drug_ctrl_cell_exprt), condition=exprt_design_table_drug_ctrl_cell_exprt$State, replicate=cumsumGroups(exprt_design_table_drug_ctrl_cell_exprt$State), stringsAsFactors=FALSE)
            if(verbose) print(exprt_design_drug_ctrl_cell_exprt)

            # Each row must have a minimum number of LFQ intensity values available at drug and control conditions.
            sample_lfq_intsty_drug_ctrl_cell_exprt <- as.matrix(sample_lfq_intsty_drug_ctrl_cell_exprt)
            sample_lfq_intsty_drug_ctrl_cell_exprt_non_na_flags <- !is.na(sample_lfq_intsty_drug_ctrl_cell_exprt)
            min_n_row_vals_drug_flags <- rowSums(sample_lfq_intsty_drug_ctrl_cell_exprt_non_na_flags[,exprt_design_drug_ctrl_cell_exprt$condition==drug_name,drop=FALSE]) >= 1
            min_n_row_vals_ctrl_flags <- rowSums(sample_lfq_intsty_drug_ctrl_cell_exprt_non_na_flags[,exprt_design_drug_ctrl_cell_exprt$condition==state_name_ctrl,drop=FALSE]) >= 1
            min_n_row_vals_drug_ctrl_flags <- min_n_row_vals_drug_flags & min_n_row_vals_ctrl_flags
            if(!any(min_n_row_vals_drug_ctrl_flags)) next

            n_compr_pairs <- n_compr_pairs + 1
            if(verbose) cat("Comparison #", n_compr_pairs, "\n", sep="")

            # Construct a design model.
            drug_name_syntax <- gsub("[+-]", ".", drug_name)
            cond_groups <- as.factor(gsub("[+-]", ".", exprt_design_drug_ctrl_cell_exprt$condition))
            exprt_design_model <- model.matrix(~0+cond_groups) # fitting without intercept
            colnames(exprt_design_model) <- gsub("cond_groups", "", colnames(exprt_design_model))

            # Extract LFQ intensity data for current compared samples at drug-treated and control conditions.
            sample_lfq_intsty_drug_ctrl_cell_exprt <- sample_lfq_intsty_drug_ctrl_cell_exprt[min_n_row_vals_drug_ctrl_flags,,drop=TRUE]
            # Remove all rows with NAs from LFQ intensity data.
            sample_lfq_intsty_drug_ctrl_cell_exprt <- sample_lfq_intsty_drug_ctrl_cell_exprt[!matrixStats::rowAnyNAs(sample_lfq_intsty_drug_ctrl_cell_exprt),,drop=FALSE]

            # Transform LFQ intensity data.
            # Stablize and reduce replicate variance.
            vsn_fit_results <- vsn::vsnMatrix(sample_lfq_intsty_drug_ctrl_cell_exprt, verbose=FALSE)
            sample_lfq_intsty_trans_drug_ctrl_cell_exprt <- vsn::predict(vsn_fit_results, sample_lfq_intsty_drug_ctrl_cell_exprt)

            # Fit the LFQ intensity data with linear model.
            lm_fit_results <- limma::lmFit(sample_lfq_intsty_trans_drug_ctrl_cell_exprt, design = exprt_design_model)
            contr_mat <- limma::makeContrasts(contrasts=paste(drug_name_syntax,state_name_ctrl,sep="-"), levels=exprt_design_model)
            contr_fit_results <- limma::contrasts.fit(lm_fit_results, contrasts = contr_mat)

            # Compute all kinds of comparison statistics with specified options for
            # variance trend estimation and fold change cutoff.
            # Use limma's method for variance trend estimation.
            ebayes_fit_results <- limma::eBayes(contr_fit_results, trend=TRUE)

            # Estimate prior variance trend as needed and extract comparison results.
            # Use limma's pipeline for extracting comparison results.
            limma_results <- limma::topTreat(ebayes_fit_results, number=nrow(ebayes_fit_results))

            # Extract information of differentially expressed proteins/genes according
            # to specified FDR threshold.
            expr_mean_vals <- limma_results$AveExpr
            expr_logfc_vals <- limma_results$logFC
            dep_flags <- limma_results$adj.P.Val < fdr_thrsh
            pos_logfc_flags <- limma_results$logFC > 0
            dep_names <- rownames(limma_results[dep_flags,,drop=FALSE])

            # Extract and save DEP comparison statistics results.
            dep_compr_stats <- limma_results[, c("logFC", "AveExpr", "t", "P.Value", "adj.P.Val"), drop=FALSE]
            colnames(dep_compr_stats) <- c("logFC", "logCPM", "t", "PValue", "FDR")

            # Remove the t statistics column from DEP comparison statistics table.
            dep_compr_stats[["t"]] <- NULL

            # Add a Regulation column to DEP comparison statistics table.
            dep_regulates <- rep(0, times=length(dep_flags))
            dep_regulates[dep_flags] <- 1
            dep_regulates <- dep_regulates * sign(dep_compr_stats$logFC)
            dep_compr_stats <- data.frame(dep_compr_stats, Regulation=dep_regulates, stringsAsFactors=FALSE)

            # Record DEP comparison summary table, save DEP comparison statistics results, and
            # generate M-A plots.
            if(length(dep_names)>0)
            {
                if(verbose) cat(drug_name, " in #", exprt_num, " ", cell_line, " has ", length(dep_names), " DEPs: ", paste0(dep_names,collapse=", "), "\n", sep="")

                # Record DEP comparison summary.
                dep_compr_stats_sumry <- rbind(dep_compr_stats_sumry, data.frame(Drug=drug_name, Cell=cell_line, Exp=exprt_num, N.DEPs=length(dep_names), DEPs=paste0(dep_names,collapse=";"), stringsAsFactors=FALSE))
            }

            # Combine comparison statistics results with original and normalized LFQ intensity.
            stopifnot(identical(colnames(sample_lfq_intsty_drug_ctrl_cell_exprt), colnames(sample_lfq_intsty_trans_drug_ctrl_cell_exprt)))
            stopifnot(identical(rownames(sample_lfq_intsty_drug_ctrl_cell_exprt), rownames(sample_lfq_intsty_trans_drug_ctrl_cell_exprt)))
            sample_names_drug_ctrl_cell_exprt <- colnames(sample_lfq_intsty_drug_ctrl_cell_exprt)
            sample_lfq_intsty_orig_trans_drug_ctrl_cell_exprt <- cbind(sample_lfq_intsty_drug_ctrl_cell_exprt, sample_lfq_intsty_trans_drug_ctrl_cell_exprt)
            colnames(sample_lfq_intsty_orig_trans_drug_ctrl_cell_exprt) <- c(sample_names_drug_ctrl_cell_exprt, paste(sample_names_drug_ctrl_cell_exprt,"Norm",sep="."))
            stopifnot(setequal(rownames(sample_lfq_intsty_drug_ctrl_cell_exprt), rownames(dep_compr_stats)))
            sample_lfq_intsty_orig_trans_drug_ctrl_cell_exprt <- sample_lfq_intsty_orig_trans_drug_ctrl_cell_exprt[order(match(rownames(sample_lfq_intsty_orig_trans_drug_ctrl_cell_exprt), rownames(dep_compr_stats))),]
            dep_compr_stats_results_drug_cell_exprt <- data.frame(sample_lfq_intsty_orig_trans_drug_ctrl_cell_exprt, dep_compr_stats, stringsAsFactors=FALSE)

            # Sort comparison statistics results according to FDR and p-value.
            dep_compr_stats_results_drug_cell_exprt <- dep_compr_stats_results_drug_cell_exprt[ order( xtfrm(dep_compr_stats_results_drug_cell_exprt[,"FDR"]), xtfrm(dep_compr_stats_results_drug_cell_exprt[,"PValue"]) ), ]

            # Record DEP comparison statistics results for current experiment number.
            dep_compr_stats_results_list_drug_cell[[as.character(exprt_num)]] <- dep_compr_stats_results_drug_cell_exprt
        }
        # Process DEP comparison statistics results for current cell line.
        if(length(dep_compr_stats_results_list_drug_cell) > 0)
        {
            # Retrieve the complete set of gene names from all experiments.
            gene_names_union <- NULL
            for (exprt_num in names(dep_compr_stats_results_list_drug_cell))
            {
                if(is.null(gene_names_union)) gene_names_union <- rownames(dep_compr_stats_results_list_drug_cell[[exprt_num]])
                else gene_names_union <- union(gene_names_union, rownames(dep_compr_stats_results_list_drug_cell[[exprt_num]]))
            }
            # Collect the logFC, logCPM, p-value and FDR from multiple experiments.
            gene_exprt_logfc_table <- NULL
            gene_exprt_logcpm_table <- NULL
            gene_exprt_pvalue_table <- NULL
            gene_exprt_fdr_table <- NULL
            for (exprt_num in names(dep_compr_stats_results_list_drug_cell))
            {
                # Perform exact match with row names of data.frame because the subsetting
                # operator [ always partially match row names.
                gene_names_union_idx <- match(gene_names_union, rownames(dep_compr_stats_results_list_drug_cell[[exprt_num]]))
                # Collect logFC.
                if(is.null(gene_exprt_logfc_table)) gene_exprt_logfc_table <- dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"logFC",drop=FALSE]
                else gene_exprt_logfc_table <- cbind(gene_exprt_logfc_table, dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"logFC",drop=FALSE])
                # Collect logCPM.
                if(is.null(gene_exprt_logcpm_table)) gene_exprt_logcpm_table <- dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"logCPM",drop=FALSE]
                else gene_exprt_logcpm_table <- cbind(gene_exprt_logcpm_table, dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"logCPM",drop=FALSE])
                # Collect p-value.
                if(is.null(gene_exprt_pvalue_table)) gene_exprt_pvalue_table <- dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"PValue",drop=FALSE]
                else gene_exprt_pvalue_table <- cbind(gene_exprt_pvalue_table, dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"PValue",drop=FALSE])
                # Collect FDR.
                if(is.null(gene_exprt_fdr_table)) gene_exprt_fdr_table <- dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"FDR",drop=FALSE]
                else gene_exprt_fdr_table <- cbind(gene_exprt_fdr_table, dep_compr_stats_results_list_drug_cell[[exprt_num]][gene_names_union_idx,"FDR",drop=FALSE])
            }
            rownames(gene_exprt_logfc_table) <- gene_names_union
            colnames(gene_exprt_logfc_table) <- names(dep_compr_stats_results_list_drug_cell)
            rownames(gene_exprt_logcpm_table) <- gene_names_union
            colnames(gene_exprt_logcpm_table) <- names(dep_compr_stats_results_list_drug_cell)
            rownames(gene_exprt_pvalue_table) <- gene_names_union
            colnames(gene_exprt_pvalue_table) <- names(dep_compr_stats_results_list_drug_cell)
            rownames(gene_exprt_fdr_table) <- gene_names_union
            colnames(gene_exprt_fdr_table) <- names(dep_compr_stats_results_list_drug_cell)
            # Combine logFC, logCPM, p-value and FDR from multiple experiments for each gene.
            # The flag for the uni-directional fold change of genes.
            gene_exprt_logfc_combn <- NULL
            gene_exprt_logcpm_combn <- NULL
            gene_exprt_pvalue_combn <- NULL
            gene_exprt_fdr_combn <- NULL
            for(gene_name in rownames(gene_exprt_fdr_table))
            {
                # Perform exact match with row names of data.frame because the subsetting
                # operator [ always partially match row names.
                gene_name_idx <- match(gene_name, gene_names_union)
                # Combine the p-values and FDRs from multiple experiments using Fisher's method for each gene.
                # Combine p-value using Fisher's method.
                gene_exprt_pvalues <- unlist(gene_exprt_pvalue_table[gene_name_idx,])
                gene_exprt_pvalues <- gene_exprt_pvalues[!is.na(gene_exprt_pvalues)]
                n_gene_exprt_pvalues <- length(gene_exprt_pvalues)
                stopifnot(n_gene_exprt_pvalues > 0)
                if(n_gene_exprt_pvalues > 1) pvalue_combn <- sumlog(gene_exprt_pvalues)$p
                else pvalue_combn <- gene_exprt_pvalues
                gene_exprt_pvalue_combn <- c(gene_exprt_pvalue_combn, pvalue_combn)
                # Combine FDR using Fisher's method.
                gene_exprt_fdrs <- unlist(gene_exprt_fdr_table[gene_name_idx,])
                gene_exprt_fdrs <- gene_exprt_fdrs[!is.na(gene_exprt_fdrs)]
                n_gene_exprt_fdrs <- length(gene_exprt_fdrs)
                stopifnot(n_gene_exprt_fdrs > 0)
                if(n_gene_exprt_fdrs > 1) fdr_combn <- sumlog(gene_exprt_fdrs)$p
                else fdr_combn <- gene_exprt_fdrs
                gene_exprt_fdr_combn <- c(gene_exprt_fdr_combn, fdr_combn)
                # Calculate the probability weights based on the FDR for each gene.
                gene_exprt_probs <- 1 - gene_exprt_fdrs
                gene_exprt_prob_weights <- gene_exprt_probs / sum(gene_exprt_probs)
                # Combine logFC using the mean weighted by (1 - FDR).
                gene_exprt_logfcs <- unlist(gene_exprt_logfc_table[gene_name_idx,])
                gene_exprt_logfcs <- gene_exprt_logfcs[!is.na(gene_exprt_logfcs)]
                stopifnot(length(gene_exprt_logfcs) > 0)
                gene_exprt_logfc_mean <- sum(gene_exprt_logfcs * gene_exprt_prob_weights)
                gene_exprt_logfc_combn <- c(gene_exprt_logfc_combn, gene_exprt_logfc_mean)
                # Combine logCPM using the mean weighted by (1 - FDR).
                gene_exprt_logcpms <- unlist(gene_exprt_logcpm_table[gene_name_idx,])
                gene_exprt_logcpms <- gene_exprt_logcpms[!is.na(gene_exprt_logcpms)]
                stopifnot(length(gene_exprt_logcpms) > 0)
                gene_exprt_logcpm_mean <- sum(gene_exprt_logcpms * gene_exprt_prob_weights)
                gene_exprt_logcpm_combn <- c(gene_exprt_logcpm_combn, gene_exprt_logcpm_mean)
            }
            dep_flags <- gene_exprt_fdr_combn < fdr_thrsh
            dep_regulates <- rep(0, times=length(dep_flags))
            dep_regulates[dep_flags] <- 1
            dep_regulates <- dep_regulates * sign(gene_exprt_logfc_combn)
            dep_compr_stats_combn_drug_cell <- data.frame(logFC=gene_exprt_logfc_combn, logCPM=gene_exprt_logcpm_combn, PValue=gene_exprt_pvalue_combn, FDR=gene_exprt_fdr_combn, Regulation=dep_regulates)
            rownames(dep_compr_stats_combn_drug_cell) <- gene_names_union
            # Sort combined comparison statistics results according to FDR and then p-value.
            dep_compr_stats_combn_drug_cell <- dep_compr_stats_combn_drug_cell[ order( xtfrm(dep_compr_stats_combn_drug_cell[,"FDR"]), xtfrm(dep_compr_stats_combn_drug_cell[,"PValue"]) ), ]

            # Save the summary of combined DEP comparison statistics result file.
            dep_names_drug_cell <- rownames(dep_compr_stats_combn_drug_cell)[dep_compr_stats_combn_drug_cell$FDR<fdr_thrsh]
            n_dep_names_drug_cell <- length(dep_names_drug_cell)
            if(n_dep_names_drug_cell > 0) dep_combn_compr_stats_sumry <- rbind(dep_combn_compr_stats_sumry, data.frame(Drug=drug_name, Cell=cell_line, N.DEPs=n_dep_names_drug_cell, DEPs=paste0(dep_names_drug_cell,collapse=";"), stringsAsFactors=FALSE))

            # Record DEP comparison statistics results for current cell line.
            dep_compr_stats_results_list_drug[[cell_line]][["Details"]] <- dep_compr_stats_results_list_drug_cell
            dep_compr_stats_results_list_drug[[cell_line]][["Combined"]] <- dep_compr_stats_combn_drug_cell
        }
    }
    # Record DEP comparison statistics results for current drug treatment.
    if(length(dep_compr_stats_results_list_drug) > 0) dep_compr_stats_results_list[[drug_name]] <- dep_compr_stats_results_list_drug
}

if(verbose) cat("\n", "Finished calculating differentially expressed proteins from LFQ intensity data", "\n\n", sep="")

# Save protein LFQ dataset to a RData file.

# Save DEP comparison statistics results files and combined DEP result files.
for (drug_name in names(dep_compr_stats_results_list))
{
    for (cell_line in names(dep_compr_stats_results_list[[drug_name]]))
    {
        # Save combined DEP comparison statistics result file for each drug-cell combination.
        save_dep_combn_compr_stats_results_file_name <- paste("Protein-LFQ-DEP-Combined", paste(drug_name,cell_line,sep="-"), data_table_type, sep=".")
        save_dep_combn_compr_stats_results_file_dir <- output_data_dir
        save_dep_combn_compr_stats_results_file_path <- file.path(save_dep_combn_compr_stats_results_file_dir, save_dep_combn_compr_stats_results_file_name)
        if(verbose) cat("Exporting ", save_dep_combn_compr_stats_results_file_path, "...\n", sep="")
        write.table(dep_compr_stats_results_list[[drug_name]][[cell_line]][["Combined"]], file=save_dep_combn_compr_stats_results_file_path, quote=FALSE, sep="\t", na="NA", row.names=TRUE)

        # Save DEP comparison statistics result file for each drug-cell-exprt combination.
        for (exprt_num in names(dep_compr_stats_results_list[[drug_name]][[cell_line]][["Details"]]))
        {
            dep_compr_stats_results_file_name <- paste("Protein-LFQ-DEP-Calc", paste(drug_name,cell_line,exprt_num,sep="-"), data_table_type, sep=".")
            dep_compr_stats_results_file_dir <- output_data_dir
            dep_compr_stats_results_file_path <- file.path(dep_compr_stats_results_file_dir, dep_compr_stats_results_file_name)
            if(verbose) cat("Exporting ", dep_compr_stats_results_file_path, "...\n", sep="")
            write.table(dep_compr_stats_results_list[[drug_name]][[cell_line]][["Details"]][[exprt_num]], file=dep_compr_stats_results_file_path, quote=FALSE, sep="\t", na="NA", row.names=TRUE)
        }
    }
}

# Save the summary of combined DEP comparison statistics result file.
dep_combn_compr_stats_sumry_file_name <- paste("Protein-LFQ-DEP-Combined-Summary", data_table_type, sep=".")
dep_combn_compr_stats_sumry_file_dir <- output_data_dir
dep_combn_compr_stats_sumry_file_path <- file.path(dep_combn_compr_stats_sumry_file_dir, dep_combn_compr_stats_sumry_file_name)
if(verbose) cat("Exporting ", dep_combn_compr_stats_sumry_file_path, "...\n", sep="")
write.table(dep_combn_compr_stats_sumry, file=dep_combn_compr_stats_sumry_file_path, quote=FALSE, sep="\t", na="", row.names=FALSE)

# Save the drug-DEP summary file.
dep_compr_stats_sumry_file_name <- paste("Protein-LFQ-DEP-Summary", data_table_type, sep=".")
dep_compr_stats_sumry_file_dir <- output_data_dir
dep_compr_stats_sumry_file_path <- file.path(dep_compr_stats_sumry_file_dir, dep_compr_stats_sumry_file_name)
write.table(dep_compr_stats_sumry, file=dep_compr_stats_sumry_file_path, quote=FALSE, sep="\t", na="", row.names=FALSE)
